- name: Configuring IOS devices
  hosts: ios
  gather_facts: false
  any_errors_fatal: true
  roles: 
    - border

- name: Configuring NXOS devices
  hosts: nxos
  gather_fact: false
  any_errors_fatal: yes
  roles:
    - core
